//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceBooking()
        {
            this.PatientPayments = new HashSet<PatientPayment>();
        }
    
        public int Id { get; set; }
        public int BookingId { get; set; }
        public int InvoiceId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public bool IsPaid { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> PayedUpDate { get; set; }
        public decimal OutStandingAmount { get; set; }
    
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientPayment> PatientPayments { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
